- debug:
    msg: "restoring from /backup/{{rollback_date}}/{{inventory_hostname}}"

- name: restore the config
  ios_config:
    src: "/backup/{{rollback_date}}/{{inventory_hostname}}"
    parents: interface GigabitEthernet1

          
- name: print to terminal window
  debug:
    msg: "Restore is complete for device {{inventory_hostname}} is set to {{rollback_date}} timestamp"
